### ISSUE TITLE
iiwa7 joint 3 safety limits in error?

### ISSUE THREAD

**Issue by hauptmech** [SalvoVirga/iiwa_stack#15]
I was using the iiwa7 urdf as a starting point for a model in a different format and I noticed that joint 3 has limits of +/-170 but soft limits of +/-118. Is this a copy/paste error? Or is that really the recommended soft limit?

**Comment by SalvoVirga** [comment]
Definitely an error, I even found others around the urdf. Apologies, I will fix them asap.
Thanks a lot for pointing it out!

**Comment by hauptmech** [comment]
Cool. I don't have an iiwa7 so I'll look for the updates to update my [non-xacro native python description](https://github.com/hauptmech/odio_urdf/tree/master/test/iiwa7).
