### ISSUE TITLE
No robotNamespace element found in transmission

### ISSUE THREAD

**Issue by muhrix** [SalvoVirga/iiwa_stack#23]
Hi,

First of all, I am running ROS Indigo and Gazebo 5.3.0 on Ubuntu 14.04.

I tried to run the `iiwa_gazebo.launch` file (from `master` branch, with default argument values) and the controllers failed to initialise due to missing `<robotNamespace>` elements within the `<transmission>` elements in `iiwa.transmission.xacro`.

I added the missing `<robotNamespace>` elements to all 7 `<transmission>` elements as below and the controllers loaded successfully:

```xml
<transmission name="iiwa_tran_1">
      <robotNamespace>/${robot_name}</robotNamespace>
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="iiwa_joint_1">
```

Is that something exclusive to my setup/Gazebo version? Have you experienced this issue before?

I'd be happy to open a pull request if you like!

Thanks a lot!

**Comment by SalvoVirga** [comment]
Hi, 
I tried to quick test it, but I'm on a machine with some experimental settings and gazebo crashes right away. Could you open a pull request in the meantime? I will test everything on a clean virtual machine asap.

Thanks !
