### ISSUE TITLE
R800 inertial parameters

### ISSUE THREAD

**Issue by ahundt** [SalvoVirga/iiwa_stack#35]
useful links for determining inertial parameters of kuka iiwa R800:

https://www.google.co.in/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=Dynamic+Identification+of+Manipulator%3A+Comparison+between+CAD+and+Actual+Parameters

http://www.inacomm2015.ammindia.org/img/94.pdf

These could be incorporated into the urdf. 

@Ahyan1 you may be interested in this based on https://github.com/SalvoVirga/iiwa_stack/issues/11.

**Comment by SalvoVirga** [comment]
Thanks for the reference Andrew, we will definitely add the inertial values to the model.

**Comment by SalvoVirga** [comment]
We integrated the inertial values in the URDF with the last release. Thanks a lot again!

**Comment by ahundt** [comment]
@SalvoVirga what's the relevant commit? Thanks!

**Comment by SalvoVirga** [comment]
3d872d9
