### ISSUE TITLE
Support of Sunrise.OS 1.11

### ISSUE THREAD

**Issue by gekoraus** [SalvoVirga/iiwa_stack#36]
As I need some features of Sunrise.OS 1.11, I was wondering if you are planning to support this version in the future?
In the FAQ is written, that normally only tiny changes are needed to support newer versions, so I'll probably also try for myself if I can get it to work.

**Comment by SalvoVirga** [comment]
I got Sunrise.OS 1.11 few days ago. From what I've quickly seen, only a small change in [ROSSmartServo.java](https://github.com/SalvoVirga/iiwa_stack/blob/master/iiwa_ros_java/src/de/tum/in/camp/kuka/ros/ROSSmartServo.java#L304-L309).
Lines 304-309 should become something like : 

```
case CARTESIAN_POSE: {
     PoseStamped commandPosition = subscriber.getCartesianPose();
     Transformation tr = helper.rosPoseToKukaTransformation(commandPosition.getPose());
     Frame destinationFrame = new Frame(tr);
     if (robot.isReadyToMove())
         motion.getRuntime().setDestination(destinationFrame);
}
```
But I didn't have the time to test 1.11 on the real robot. This should be the only change needed.
Let me know if everything is fine for you, I will probably install 1.11 on my robot later next week.

**Comment by SalvoVirga** [comment]
branch [/feature/Sunrise1.11](https://github.com/SalvoVirga/iiwa_stack/tree/feature/Sunrise1.11) now supports the correspondent version, soon to be merged in master

**Comment by gekoraus** [comment]
Thank you very much! I just updated and everything is working as expected!
