### ISSUE TITLE
iiwa7 xacro file error

### ISSUE THREAD

**Issue by LinYuChi** [SalvoVirga/iiwa_stack#64]
Hi,

There are some transform error in the iiwa7 xacro file cause link 3 of the robot not rotating to the joint 3 center. I saw this small displacement when I rotates joint 3:

![joint_3_off](https://cloud.githubusercontent.com/assets/5383492/24256276/212532f8-0fbe-11e7-9a14-937820ecb8d1.png)

Later I found that there are some overlapping in link 1 and link 2:

![link1_2_overlapping](https://cloud.githubusercontent.com/assets/5383492/24256914/d04b63aa-0fbf-11e7-9352-c32a1e10f7d8.png)

By changing the origin of link 2 from (0,0,-0.006) to (0,0,0) and link 3 from (0,-0.005,-0.026) to (0,0,-0.026). The problem goes away without changing the transform of the links.

I tested both in OpenRAVE using or_urdf, and in RViz, they showed the same result.

**Comment by SalvoVirga** [comment]
Great! I was aware of this visual error, but since the transforms were still correct I didn't want to play around with the meshes. I would be the best if you could open a pull request with the changes, else I will do that myself in the next days.

**Comment by SalvoVirga** [comment]
fixed with #66
