### ISSUE TITLE
Wiki installation instructions cabinet_setup

### ISSUE THREAD

**Issue by felixvd** [SalvoVirga/iiwa_stack#65]
I have set up iiwa_stack on three robots now and have feedback. Maybe you can amend the wiki page accordingly.

- One of our newer arms would not display the login screen if both a DVI cable and the smartPAD were connected to the robot. The smartPAD has to be disconnected to follow the instructions.
- It helps to open the device manager and the network adapter settings and to note which adapters exist before doing step 3 (it should be only the Realtime OS Virtual Network Adapter (IRQ)).
- I never had to install drivers as described in step 4. I wouldn't know how to install the files either, so this confused me on my first try.
- On the latest robot, the Network adapter appeared without rebooting.
- It may be good to put in an explicit warning such as "Do not change the settings of the Realtime OS Virtual Network Adapter. The network adapter you want is a different one." It didn't happen to us, but almost. It's an easy mistake to make.

Apart from that, we also added our robot (160.69.69.100) as the default DNS server. Otherwise, you have to set up the hostname on the ROSCORE PC to be its IP address, which is not very pretty. This was often the cause for the robot sending its state, but not reacting to commands.

**Comment by SalvoVirga** [comment]
Thank a lot for the feedback! I changed the wiki accordingly and point at this issue as reference
