### ISSUE TITLE
Dead link on wiki

### ISSUE THREAD

**Issue by UPedrou** [SalvoVirga/iiwa_stack#70]
Hello.
I was trying to see the full example of command the robot using move it, but when I try to open the link https://github.com/SalvoVirga/iiwa_stack_examples/blob/master/iiwa_tool_examples/src/command_robot_moveit.cpp
It give me and 404 error.

**Comment by SalvoVirga** [comment]
Fixed, thanks for pointing it out. Feel free to reopen it or comment if you find any other mistake.
