### ISSUE TITLE
How to connect LBR IIWA Kuka with ROS by using IIWA-Stack

### ISSUE THREAD

**Issue by usman2k** [SalvoVirga/iiwa_stack#74]
Could you please describe me step by step process connect LBR IIWA Kuka(7R800) with ROS (Indigo) by using IIWA-Stack.. And it will be more fruitful if there will be some video tutorial regarding this...

**Comment by SalvoVirga** [comment]
Did you have a look at the [Wiki](https://github.com/SalvoVirga/iiwa_stack/wiki) already?
There I tried to describe all the setup process.

**Comment by usman2k** [comment]
Could you please send me the link


________________________________

**Comment by SalvoVirga** [comment]
I just did in the previous comment... -> https://github.com/SalvoVirga/iiwa_stack/wiki
It is also in the readme of this repo

**Comment by usman2k** [comment]
Thanks alot for your kindness...

Is there any video tutorial regarding this... It will be more convenient to understand the process...

Best Regards,

Usman Ishtiaq


________________________________

**Comment by SalvoVirga** [comment]
No videos at the moment, the instructions on the wiki should be clear tho.
Open an issue on specific problems/doubts if you have any during the setup.
