### ISSUE TITLE
Could not create controller 'KUKA_Sunrise_Cabinet_1'

### ISSUE THREAD

**Issue by aravindsiv** [SalvoVirga/iiwa_stack#90]
Hi,

I'm facing an issue similar to the one described in the middle of the comments section of #13 where I get the following error on C:\KRC\ApplicationServer\AppServer.exe:

![kuka_error](https://user-images.githubusercontent.com/5090106/32398057-2fe72df8-c0c3-11e7-9647-a5e6a8372e30.jpg)

As a result, on my smartPAD, I cannot see any connected robots, as shown below:

![smartpad_error](https://user-images.githubusercontent.com/5090106/32398071-419959f4-c0c3-11e7-8534-226661e9aa44.jpg)

Any idea what could be going on, and what I can do to fix it? When I encountered this earlier, a simple reboot of the controller helped (as @SalvoVirga suggested on #13), though that no longer seems to be the case.

Thanks in advance!

**Comment by aravindsiv** [comment]
Found a fix for this (albeit temporarily):

Just connect a monitor, keyboard and mouse to the controller, and close the C:\KRC\ApplicationServer\AppServer.exe window. Once you close it, follow the same path and restart the AppServer (don't use the desktop icon, it doesn't work for some reason).

Waiting to hear back from you guys so that I can close this issue for good.

**Comment by SalvoVirga** [comment]
It sounds like a random behavior from the KUKA controller, if you are ok with it you can close the issue. Still, it might be a good reference for someone who encounter the same problem.
